export const UserEditSteps = {
	BASIC: 'BASIC',
	APPEARANCE: 'APPEARANCE',
	DOCTORINE: 'DOCTORINE',
	PROFESSION: 'PROFESSION',
	EDUCATION: 'EDUCATION',
	LIFESTYLE: 'LIFESTYLE',
	FAMILY: 'FAMILY',
	CONTACT: 'CONTACT',
	ADDRESS: 'ADDRESS',
};
